# wrangler.toml

name = "qibeads-ai" # Should match your Cloudflare Pages project name
main = "_worker.js" # Entry point for the Worker
compatibility_date = "2024-05-02" # Use a recent compatibility date

[pages_build_output_dir]
# This tells Pages where your static assets (like index.html) are.
# Since index.html is in the root, we use ".", but Pages usually defaults
# to detecting this or using a specific build output dir if a build command is set.
# For a pure Worker setup with static assets alongside, often just setting `main` is enough,
# but explicitly setting this can sometimes help.
# If you only have `_worker.js` and `index.html` in the root,
# Cloudflare might automatically figure this out. Let's omit it for now to keep it simple.
# If deployment fails finding assets, uncommenting and setting to "." might be needed.
# dir = "."

# By having a wrangler.toml and dependencies in package.json,
# Cloudflare Pages build system should automatically bundle the worker and its dependencies. 