# wrangler.toml

name = "qibeads-ai" # Should match your Cloudflare Pages project name
# main = "_worker.js" # REMOVED: Not used for Pages projects with Functions
compatibility_date = "2024-05-02" # Use a recent compatibility date

# This tells Pages where your static assets (like index.html) are.
# Pages will automatically detect _worker.js in this directory.
pages_build_output_dir = "."

# By having a wrangler.toml and dependencies in package.json,
# Cloudflare Pages build system should automatically bundle the worker and its dependencies. 